// port-lint: source src/windows_sys.rs
package io.github.kotlinmania.syslocale

// Bindings generated by `windows-bindgen` 0.51.1.
//
// On Kotlin/Native mingwX64 the corresponding declarations are provided by
// `platform.windows`:
//   external fun GetUserPreferredUILanguages(
//       dwFlags: DWORD,
//       pulNumLanguages: CPointer<ULONGVar>?,
//       pwszLanguagesBuffer: PWSTR?,
//       pcchLanguagesBuffer: CPointer<ULONGVar>?,
//   ): BOOL
//   typealias BOOL = Int
//   const val MUI_LANGUAGE_NAME: UInt = 8u
//   typealias PWSTR = CPointer<UShortVar>
//   const val TRUE: BOOL = 1
//
// The Kotlin port imports those symbols directly from `platform.windows`; this
// file is a translation ledger of the upstream `extern "system"` block so that
// the 1 Rust file -> 1 Kotlin file mapping is preserved.
